import { useEffect, useState } from "react";
import heroVideo from "../assets/rainforest3.mp4";
import textureVideo from "../assets/leaf-texture.mp4";
import jatiVideo from "../assets/jativideo2.mp4";
import gftLogo from "../assets/GFTlogo4.png";

export default function Home() {
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    const handleResize = () => setIsMobile(window.innerWidth < 768);
    handleResize();
    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  return (
    <div style={pageWrapper}>
      {/* SCROLL SUAVE */}
      <style>
        {`
          html {
            scroll-behavior: smooth;
          }
        `}
      </style>

      {/* BACKGROUND TEXTURE */}
      <video autoPlay loop muted playsInline style={textureVideoStyle(isMobile)}>
        <source src={textureVideo} type="video/mp4" />
      </video>

      <div style={contentLayer}>
        {/* NAVIGATION MENU */}
        <nav style={navStyle}>
          <ul style={navListStyle}>
            <li><a href="#hero" style={navLinkStyle}>Home</a></li>
            <li><a href="#gft" style={navLinkStyle}>GFT Info</a></li>
            <li><a href="#jatimana" style={navLinkStyle}>Jatimanã Lake</a></li>
            <li><a href="#metadata" style={navLinkStyle}>On-Chain</a></li>
            <li><a href="#support" style={navLinkStyle}>Support the Forest</a></li>
          </ul>
        </nav>

        {/* HERO VIDEO */}
        <section style={heroVideoSection} id="hero">
          <video
            src={heroVideo}
            autoPlay
            loop
            muted
            playsInline
            style={heroVideoStyle}
          />
        </section>

        {/* HERO CONTENT */}
        <section style={heroContent(isMobile)} id="hero-content">
          <span style={eyebrowStyle}>
            Amazon Rainforest Conservation • Digital Transparency • Verified Impact
          </span>

          <h1 style={heroTitle(isMobile)}>
            Protecting the Amazon through transparent, verifiable conservation
          </h1>

          <p style={heroSubtitle}>
            Rainforest Conservancy is a conservation initiative dedicated to the
            long-term protection of the Amazon rainforest through measurable,
            technology-driven environmental stewardship. By connecting preserved
            forest ecosystems to verifiable digital frameworks such as the Geo
            Forest Token (GFT), the project enables transparency, accountability,
            and real-world environmental impact.
          </p>
        </section>

        {/* GFT INFO */}
        <section style={{ ...section, textAlign: "center" }} id="gft">
          <a href="https://geoforesttoken.io/" target="_blank" rel="noreferrer">
            <img src={gftLogo} alt="GFT Logo" style={{ ...gftLogoStyle, margin: "0 auto", display: "block" }} />
          </a>

          <h2 style={{
              ...sectionTitle,
              textAlign: "center",
              margin: "20px auto",
              maxWidth: "800px",
              lineHeight: "1.4",
            }}>
            Geo Forest Token (GFT) — A Digital Framework for Forest Conservation
          </h2>

          <div style={{ maxWidth: "800px", margin: "0 auto" }}>
            <p style={{ ...sectionText, textAlign: "center" }}>
              The Geo Forest Token (GFT) is a climate technology initiative that
              integrates blockchain, regenerative finance, and advanced environmental
              conservation strategies to support rainforest protection and create a
              <strong> new forest economy</strong>. GFT transforms verified ecosystem services
              generated by conserved forests into <strong>real-world digital assets (RWA)</strong>
              that are georeferenced, auditable, and tradable, providing measurable
              impact while ensuring transparency and accountability. 
            </p>

            <p style={{ ...sectionText, textAlign: "center" }}>
              Each GFT ESG Digital Token can be backed by preserved forest areas or
              sustainably managed lands, with <strong>technical monitoring through remote
              sensing and field data</strong>. By acquiring these tokens, investors can
              directly support environmental conservation, contribute to sustainable
              use of natural resources, and own an asset with liquidity potential in
              secondary markets.
            </p>

            <p style={{ ...sectionText, textAlign: "center" }}>
              GFT offers significant value propositions for investors and companies:
            </p>

            <ul style={{ ...sectionText, display: "inline-block", textAlign: "left", paddingLeft: "0", listStylePosition: "inside" }}>
              <li><strong>1. ESG Alignment:</strong> Tokens enable concrete progress
              toward ESG goals and reduction of climate risk exposure, making them
              attractive for impact-focused portfolios.</li>

              <li><strong>2. Real Asset Backing:</strong> Each token is linked to
              tangible ecosystem services like carbon sequestration, biodiversity
              protection, and water cycle regulation — providing intrinsic value
              beyond speculation.</li>

              <li><strong>3. Impact and Community Benefits:</strong> Part of the
              project’s revenue supports local communities, socio-biodiversity
              value chains, and small producers in the Amazon region.</li>

              <li><strong>4. Market Differentiation & Brand Value:</strong> Investing
              in and adopting GFT can strengthen corporate reputation, enhance
              sustainability reporting, and offer green marketing opportunities.</li>

              <li><strong>5. Partnership & Monetization:</strong> Landowners with
              conserved native forests can partner with GFT to generate continuous
              income through carbon credits and ecosystem service tokenization.</li>
            </ul>

            <p style={{ ...sectionText, textAlign: "center" }}>
              One example project is <strong>GFT-01 – Lago do Jatimana</strong>, where
              tokens are created and sold based on ecosystem services generated
              annually on conserved land in the Vale do Javari, Amazonas. Each token
              corresponds to one hectare of preserved forest per year, supporting
              carbon capture, habitat protection, water conservation, and climate
              regulation.
            </p>

            <p style={{ ...sectionText, textAlign: "center" }}>
              By investing in GFT, stakeholders not only participate in a <strong>financial
              asset with growth potential</strong>, but also help drive <strong>sustainable
              development, forest preservation, and community empowerment</strong>, aligning
              financial interests with real-world environmental impact.
            </p>
          </div>
        </section>

        {/* JATIMANÃ PROJECT */}
        <section style={{ ...altSection, textAlign: "center" }} id="jatimana">
          <div style={jatiVideoWrapper}>
            <video
              src={jatiVideo}
              autoPlay
              loop
              muted
              playsInline
              style={{ ...jatiVideoStyle, margin: "0 auto", display: "block" }}
            />
          </div>

          <h2 style={{ ...sectionTitle, textAlign: "center", margin: "20px auto", maxWidth: "800px" }}>
            GFT-01 | Jatimanã Lake — A Verified Amazon Conservation Asset
          </h2>

          <div style={{ maxWidth: "800px", margin: "0 auto" }}>
            <p style={{ ...sectionText, textAlign: "center" }}>
              The <strong>GFT-01 Jatimanã Lake Project</strong> is a high-integrity
              environmental preservation initiative located in the heart of the Brazilian
              Amazon. It protects a strategic freshwater ecosystem surrounded by primary
              rainforest, generating measurable ecosystem services with global relevance.
            </p>

            <p style={{ ...sectionText, textAlign: "center" }}>
              The project safeguards approximately <strong>1,800 hectares of preserved Amazon rainforest</strong>, ensuring
              long-term carbon sequestration, biodiversity conservation, climate
              regulation, and protection of vital water resources.
            </p>

            <p style={{ ...sectionText, textAlign: "center" }}>
              The protected area is part of the rural property known as <strong>Conceição</strong>, located in <strong>Atalaia do Norte</strong>, Amazonas, Brazil — within the highly
              sensitive and ecologically significant <strong>Vale do Javari region</strong>, one of the most preserved rainforest
              areas in the world.
            </p>

            <p style={{ ...sectionText, textAlign: "center" }}>
              Jatimanã Lake is naturally connected to the Amazonian river system through
              seasonal floodplains, forming a complex network of lakes, igarapés, and
              waterways that support rich aquatic life, including native fish species,
              reptiles, birds, and endemic fauna.
            </p>

            <p style={{ ...sectionText, textAlign: "center" }} id="metadata">
              Each <strong>GFT (Green Forest Token)</strong> represents <strong>one hectare of preserved rainforest per year</strong>, certified and
              aligned with ecosystem service valuation methodologies. The model assigns an
              annual environmental value of <strong>US$737 per hectare</strong>, reflecting its contribution to carbon
              capture, biodiversity protection, and climate mitigation.
            </p>

            <p style={{ ...sectionText, textAlign: "center" }}>
              The GFT-01 Jatimanã Lake Project offers investors exposure to a tangible,
              nature-based asset backed by real land preservation, transparent geographic
              data, and long-term environmental impact within one of the most important
              biomes on Earth.
            </p>

            {/* ================= ON-CHAIN METADATA ================= */}
            <div style={{ ...metadataBox, marginTop: "60px" }}>
              <h3 style={{ ...metaTitle, textAlign: "center", marginBottom: "32px" }}>
                On-Chain Transparency
              </h3>

              <div style={metaGrid}>
                <div style={metaItem}>
                  <h4 style={metaLabel}>Contract Address</h4>
                  <p style={metaValue}>
                    0xc23d925684919c1619f13427817d3fee6c24debb
                  </p>
                </div>

                <div style={metaItem}>
                  <h4 style={metaLabel}>Token Standard</h4>
                  <p style={metaValue}>ERC-721</p>
                </div>

                <div style={metaItem}>
                  <h4 style={metaLabel}>Blockchain</h4>
                  <p style={metaValue}>Ethereum (ETH)</p>
                </div>

                <div style={metaItem}>
                  <h4 style={metaLabel}>Owner Address</h4>
                  <p style={metaValue}>
                    0x598749188295a79538fc879820ef5c9747ff61b9
                  </p>
                </div>

                <div style={metaItem}>
                  <h4 style={metaLabel}>Metadata</h4>
                  <a
                    href="https://metadata.mintable.app/mintable_gasless/40494872365929988429502935789721658141196506675116677701762907237175745074785"
                    target="_blank"
                    rel="noopener noreferrer"
                    style={metaLink}
                  >
                    View On-Chain Record ↗
                  </a>
                </div>
              </div>

              <p style={{ ...tableNote, marginTop: "24px", textAlign: "center" }}>
                This asset leverages blockchain technology to ensure full transparency,
                immutability, and public verification of ownership and metadata.
              </p>
            </div>
          </div>
        </section>

        {/* ================= SUPPORT THE FOREST ================= */}
        <section style={supportSection} id="support">
          <h2 style={sectionTitle}>Support the Forest</h2>

          <div style={{ maxWidth: "800px", margin: "0 auto" }}>
            <p style={sectionText}>
              Your support helps us protect the Amazon rainforest, preserve biodiversity,
              and empower local communities. Every contribution enables:
            </p>

            <ul style={{ ...sectionText, paddingLeft: "20px", listStyleType: "disc" }}>
              <li><strong>Forest Preservation:</strong> Funding conservation projects that safeguard critical ecosystems.</li>
              <li><strong>Community Empowerment:</strong> Supporting sustainable livelihoods and education for local communities.</li>
              <li><strong>Scientific Research:</strong> Monitoring wildlife, carbon capture, and ecological health.</li>
              <li><strong>Technology Integration:</strong> Implementing digital tracking with GFT for transparent impact.</li>
            </ul>

            <p style={sectionText}>
              Your donations or partnerships create a measurable impact while contributing
              to the long-term sustainability of the Amazon rainforest. Together, we can
              ensure that this vital ecosystem thrives for generations to come.
            </p>

            <a href="mailto:preservetheforest@outlook.com" style={supportButton}>
              Contact to Support 
            </a>
          </div>
        </section>
      </div>

      {/* ================= FOOTER ================= */}
      <footer style={footerStyle}>
        <div style={footerContent}>
          <div style={footerSection}>
            <h4 style={footerHeading}>Rainforest Conservancy</h4>
            <p style={footerText}>
              Dedicated to protecting the Amazon rainforest and supporting local communities
              through measurable conservation initiatives.
            </p>
          </div>

          <div style={footerSection}>
            <h4 style={footerHeading}>Quick Links</h4>
            <ul style={footerLinks}>
              <li><a href="#hero" style={footerLink}>Home</a></li>
              <li><a href="#gft" style={footerLink}>GFT Info</a></li>
              <li><a href="#jatimana" style={footerLink}>Jatimanã Lake</a></li>
              <li><a href="#metadata" style={footerLink}>On-Chain</a></li>
              <li><a href="#support" style={footerLink}>Support the Forest</a></li>
            </ul>
          </div>

          <div style={footerSection}>
            <h4 style={footerHeading}>Contact</h4>
            <p style={footerText}>Email: <a href="mailto:preservetheforest@outlook.com" style={footerLink}>preservetheforest@outlook.com</a></p>
            <p style={footerText}>Location: Amazonas, Brazil</p>
          </div>
        </div>

        <div style={footerBottom}>
          <p style={{ margin: 0 }}>
            &copy; {new Date().getFullYear()} Rainforest Conservancy. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}

/* ================= STYLES ================= */
const pageWrapper = { position: "relative", minHeight: "100vh" };
const contentLayer = { position: "relative", zIndex: 1 };
const textureVideoStyle = isMobile => ({
  position: "fixed",
  inset: 0,
  width: "100%",
  height: "100%",
  objectFit: "cover",
  opacity: isMobile ? 0.06 : 0.1,
  zIndex: -1
});
const heroVideoSection = { height: "100svh", overflow: "hidden" };
const heroVideoStyle = { width: "100%", height: "100%", objectFit: "cover" };
const heroContent = isMobile => ({
  maxWidth: "900px",
  margin: "0 auto",
  padding: isMobile ? "80px 20px" : "150px 24px",
  textAlign: "center"
});
const eyebrowStyle = { fontSize: "0.75rem", letterSpacing: "0.15em", textTransform: "uppercase", color: "#1F7A4D", marginBottom: "20px" };
const heroTitle = isMobile => ({ fontSize: isMobile ? "2.2rem" : "3.2rem", marginBottom: "24px" });
const heroSubtitle = { lineHeight: 1.8, fontSize: "1.05rem" };
const section = { maxWidth: "1080px", margin: "0 auto", padding: "120px 24px" };
const altSection = { ...section, background: "rgba(255,255,255,0.9)" };
const sectionTitle = { fontSize: "2rem", marginBottom: "24px" };
const sectionText = { maxWidth: "760px", lineHeight: 1.8, marginBottom: "24px" };
const gftLogoStyle = { display: "block", margin: "0 auto 56px", maxWidth: "680px", filter: "drop-shadow(0 18px 40px rgba(0,0,0,.18))" };
const jatiVideoWrapper = { borderRadius: "20px", overflow: "hidden", marginBottom: "48px" };
const jatiVideoStyle = { width: "100%", height: "420px", objectFit: "cover" };
const metadataBox = { marginTop: "48px" };
const metaTitle = { fontSize: "1.4rem", marginBottom: "24px" };
const metaGrid = { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: "28px", marginTop: "24px" };
const metaItem = { padding: "24px", borderRadius: "16px", background: "rgba(31, 122, 77, 0.05)", border: "1px solid rgba(31, 122, 77, 0.15)", boxShadow: "0 8px 20px rgba(0,0,0,0.08)", display: "flex", flexDirection: "column", gap: "10px" };
const metaLabel = { fontSize: "0.85rem", textTransform: "uppercase", letterSpacing: "0.12em", opacity: 0.75, margin: 0 };
const metaValue = { margin: 0, fontSize: "0.95rem", wordBreak: "break-all", color: "#1F7A4D", fontWeight: 500 };
const metaLink = { display: "inline-block", color: "#1F7A4D", fontWeight: 600, textDecoration: "none", transition: "color 0.3s ease" };
const tableNote = { marginTop: "16px", fontSize: "0.85rem", opacity: 0.6 };

const supportSection = { maxWidth: "1080px", margin: "0 auto", padding: "120px 24px", textAlign: "center", backgroundColor: "rgba(240, 255, 245, 0.95)", borderRadius: "20px", boxShadow: "0 12px 36px rgba(0,0,0,0.08)" };
const supportButton = { display: "inline-block", marginTop: "32px", padding: "14px 36px", backgroundColor: "#1F7A4D", color: "#fff", fontWeight: 600, fontSize: "1rem", borderRadius: "999px", textDecoration: "none", boxShadow: "0 6px 18px rgba(31,122,77,0.25)", transition: "transform 0.2s ease, backgroundColor 0.3s ease", cursor: "pointer" };

const navStyle = { position: "fixed", top: 0, left: 0, width: "100%", background: "rgba(255,255,255,0.95)", zIndex: 1000 };
const navListStyle = { display: "flex", justifyContent: "center", listStyle: "none", padding: "12px 0", margin: 0 };
const navLinkStyle = { margin: "0 20px", color: "#1F7A4D", fontWeight: 600, textDecoration: "none" };

const footerStyle = { backgroundColor: "#1F7A4D", color: "#fff", padding: "60px 24px 24px", borderTopLeftRadius: "20px", borderTopRightRadius: "20px", marginTop: "80px" };
const footerContent = { display: "flex", flexWrap: "wrap", justifyContent: "space-between", maxWidth: "1080px", margin: "0 auto 24px" };
const footerSection = { flex: "1 1 250px", marginBottom: "24px" };
const footerHeading = { fontSize: "1.2rem", marginBottom: "16px", fontWeight: 700 };
const footerText = { fontSize: "0.95rem", lineHeight: 1.6 };
const footerLinks = { listStyle: "none", padding: 0, margin: 0 };
const footerLink = { color: "#fff", textDecoration: "none", display: "block", marginBottom: "8px", transition: "color 0.2s ease", cursor: "pointer" };
const footerBottom = { borderTop: "1px solid rgba(255,255,255,0.2)", paddingTop: "16px", textAlign: "center", fontSize: "0.85rem" };
